### ISSUE TITLE
已经start了。在最新开发工具报错。快快更新修复吧。。

### ISSUE THREAD

**Issue by GloomHu** [yesifeng/wechat-weapp-movie#1]

**Comment by GloomHu** [comment]
微信web开发者工具 v0.12.130400

很多。。打开第一个也没就报错。。如下：
1、
./pages/my/my.wxml
 end tag missing, near 'view'
  14 |         <view class="user-location">{{userInfo.province}},{{userInfo.city}}</view>
  15 |     </view>
> 16 |     <view class="grids">
     |      ^

**Comment by yesifeng** [comment]
我的版本是v0.11.122100的，没有发现有问题。应该是IDE更新了，然后对一些api进行了修改。等更新了我再看一下。

**Comment by yesifeng** [comment]
@GloomHu 已经解决了，是因为my.wxml中的一个view标签没有正确结束。
