### ISSUE TITLE
2016-11-25  1.将网络请求从wx.request改为fetch的方式

### ISSUE THREAD

**Issue by WellLiao** [yesifeng/wechat-weapp-movie#2]
发现代码里面并没有这样做呀。在v0.12版本的工具中，fetch都不能用了

**Comment by yesifeng** [comment]
原来是用fetch的，后来改成官方的wx.request了。本来这个可以用的，因为手机上调试报错（fetch未定义），所以改成了官方的wx.request。
如果要看fetch版本的，可以看上一个版本：https://github.com/yesifeng/wechat-weapp-movie/blob/eba6601afd58da94b30ba44e4b911c0a7aeb8d78/comm/script/fetch.js
