### ISSUE TITLE
在安卓机子上不能正常使用

### ISSUE THREAD

**Issue by Jesse-Chiu** [yesifeng/wechat-weapp-movie#3]
1.  请求豆瓣数据不成功
2. 在请求数据时，导航栏的的字体一直在跳动

**Comment by yesifeng** [comment]
console中有什么错误信息吗？（手机上可以点击右上角的按钮，在弹出的选项中打开调试模式，重启小程序后即可看到console）

**Comment by yesifeng** [comment]
:white_check_mark:  已解决

问题原因：项目域名配置

解决方法：
需要在小程序后台添信任域名
- api.douban.com （豆瓣）
- api.map.baidu.com （百度地图）
https://github.com/yesifeng/wechat-weapp-movie/issues/4#issuecomment-271602709
