### ISSUE TITLE
bug3 没清空缓存，重新登录 数据丢失

### ISSUE THREAD

**Issue by wkcm** [yesifeng/wechat-weapp-movie#7]
系统类型： ios
手机品牌型号：苹果
console中的报错提示：真机
错误的截图：无
发生在什么情况下：在没有清空缓存的情况下，设置了个人资料和收藏等信息，退出后，重新登录，信息丢失。不知道算不算bug，怎么把数据保存到数据库中？

**Comment by yesifeng** [comment]
由于没有后端服务，数据是存在本地缓存的。微信退出后会对缓存进行清理，所以信息丢失。
